### ISSUE TITLE
默认配置的请求频率似乎很容易被反爬虫策略关闭下载连接？

### ISSUE THREAD

**Issue by Volundio** [zhongfly/bilibilicomic#1]
![15`E9 6$W1$TZ1XW_X09Q~5](https://user-images.githubusercontent.com/37572185/174108248-4c1cb2f8-aac6-46fc-96da-e5fe499b6377.png)

**Comment by Volundio** [comment]
以及下载顺序似乎是乱序下载的？可否能支持按章节顺序下载

**Comment by zhongfly** [comment]
1.唯一有关的也就是`max_threads`改小点，同一时间下载的图片更少。默认的10在我自己的使用中是正常的。
我看到最后一个错误是`can not connect to proxy`，我认为是你的代理不稳定，网络不佳，并不是什么反爬虫策略
2.是不是乱序我还不太清楚…毕竟我自己使用时感觉是顺序的，我之后加一个排序吧

**Comment by Volundio** [comment]
> 1.唯一有关的也就是`max_threads`改小点，同一时间下载的图片更少。默认的10在我自己的使用中是正常的。 我看到最后一个错误是`can not connect to proxy`，我认为是你的代理不稳定，网络不佳，并不是什么反爬虫策略 2.是不是乱序我还不太清楚…毕竟我自己使用时感觉是顺序的，我之后加一个排序吧

1.怪了，我同个节点用其他扒图脚本似乎都没出过这种问题。。
2.我上面截图的下载顺序就已经是乱序下载的了。。

**Comment by zhongfly** [comment]
https://github.com/zhongfly/bilibilicomic/tree/zhongfly-patch-1
你试试这个分支，应该会按升序下载了

**Comment by Volundio** [comment]
> https://github.com/zhongfly/bilibilicomic/tree/zhongfly-patch-1 你试试这个分支，应该会按升序下载了

这个分支可以按顺序下载了，感谢。提醒一下这个分支的515行忘记缩进了。

还有个问题是两个版本都无法下载特典

输入mc号（纯数字）：31351
成功使用app端登录
access_key的有效期延长失败,app is not exist
已获取漫画《乙女游戏的世界对路人角色很不友好》详情，并建立文件夹。
下载漫画章节输入y，下载特典输入n：（y/n）n
Traceback (most recent call last):
  File "BilibiliComic.py", line 709, in <module>
    main()
  File "BilibiliComic.py", line 688, in main
    manga.printList(mangaDir,isBonus=True)
  File "BilibiliComic.py", line 368, in printList
    if BonusList is None:
UnboundLocalError: local variable 'BonusList' referenced before assignment

不知道是不是这里的代码有问题
![)R7{7XQ97ML EMK%Y`(RT34](https://user-images.githubusercontent.com/37572185/174472394-9fd7ebe9-a3d5-4780-ab62-571820fcd53a.png)

**Comment by zhongfly** [comment]
那里可能是自动补全的…2个BonusList都应该改成`ep_list`

已修复，并合并至主分支

**Comment by Volundio** [comment]
> 生成的txt中就缺少ord
> 显示下载完成实际却没有下载任何文件
> 如果输入ID的话就会报错

from zhongfly:不小心编辑了你的回复，干脆就隐藏了…

**Comment by zhongfly** [comment]
忘记特典不一样了，只考虑了普通章节…
https://github.com/zhongfly/bilibilicomic/tree/fix-bonus

**Comment by Volundio** [comment]
> 忘记特典不一样了，只考虑了普通章节… https://github.com/zhongfly/bilibilicomic/tree/fix-bonus

已可用，感谢。

提点建议，可否在config.toml中的ep_str = ""的配置中提供一个可默认下载所有章节的参数？
![O}_QD$7(D~J$C{S44$GF(M7](https://user-images.githubusercontent.com/37572185/174474982-75738224-baa7-483c-bce5-6933dcaa8334.png)
特典的ID并不连续，可能需要注意下？

**Comment by zhongfly** [comment]
> > 忘记特典不一样了，只考虑了普通章节… https://github.com/zhongfly/bilibilicomic/tree/fix-bonus
> 
> 已可用，感谢。
> 
> 提点建议，可否在config.toml中的ep_str = ""的配置中提供一个可默认下载所有章节的参数？ ![O}_QD$7(D~J$C{S44$GF(M7](https://user-images.githubusercontent.com/37572185/174474982-75738224-baa7-483c-bce5-6933dcaa8334.png) 特典的ID并不连续，可能需要注意下？

不能提供默认值，如果配置文件里有默认值，就不能在命令行里输入范围了…
comic这部分设置在我预想中是已经会使用的人避免重复输入时才使用的…
和命令行一样，填入all，下载全部章节

不需要连续id的，你应该也下载成功了，也说明不需要担心是否连续会导致问题

**Comment by Volundio** [comment]
> > > 忘记特典不一样了，只考虑了普通章节… https://github.com/zhongfly/bilibilicomic/tree/fix-bonus
> > 
> > 
> > 已可用，感谢。
> > 提点建议，可否在config.toml中的ep_str = ""的配置中提供一个可默认下载所有章节的参数？ ![O}_QD$7(D~J$C{S44$GF(M7](https://user-images.githubusercontent.com/37572185/174474982-75738224-baa7-483c-bce5-6933dcaa8334.png) 特典的ID并不连续，可能需要注意下？
> 
> 不能提供默认值，如果配置文件里有默认值，就不能在命令行里输入范围了… comic这部分设置在我预想中是已经会使用的人避免重复输入时才使用的… 和命令行一样，填入all，下载全部章节
> 
> 不需要连续id的

对，我就是指all这个参数，看你提示里没有提到支持all参数还以为没有....
感谢

**Comment by zhongfly** [comment]
> 对，我就是指all这个参数，看你提示里没有提到支持all参数还以为没有.... 感谢

和命令行完全一样，我之后加提示吧
